version: "3.9"

services:
  db:
    image: postgres:16
    container_name: banking_db
    restart: always
    environment:
      POSTGRES_DB: banking
      POSTGRES_USER: banking
      POSTGRES_PASSWORD: banking
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U banking -d banking"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  db_data:
    driver: local
