server:
  port: 8089

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/banking
    username: banking
    password: banking

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: info
